export const LOADING_INDICATOR_DURATION = 1000; // 4 seconds

export const THUMB_SIZE_LIST = 'listThumb';
export const THUMB_SIZE_PREVIEW = 'previewThumb';

export const STORE_CONTACTS_INITIATED_FETCHING =
  'STORE_CONTACTS_INITIATED_FETCHING';
export const STORE_CONTACTS_COMPLETED_FETCHING =
  'STORE_CONTACTS_COMPLETED_FETCHING';
export const STORE_CONTACTS_TOGGLE_IS_FAVORITE =
  'STORE_CONTACTS_TOGGLE_IS_FAVORITE';

export const STORE_CONTACT_PREVIEW_SET = 'STORE_CONTACT_PREVIEW_SET';
export const STORE_CONTACT_PREVIEW_UNSET = 'STORE_CONTACT_PREVIEW_UNSET';
